version: '3.9'
services:

  x-vite:
    container_name: x-vite
    image: node:19-alpine
    working_dir: /usr/src/app
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./vite.config.js:/usr/src/app/vite.config.js
      - ./svelte.config.js:/usr/src/app/svelte.config.js
      - ./src:/usr/src/app/src/
      - /usr/src/app/.svelte-kit/
      - /usr/src/app/node_modules/
    restart: unless-stopped
    environment:
      PORT: 3000
    command: [ sh, -c, "npm i && npm i -g vite && npm run dev:vite" ]

  x-server:
    container_name: x-server
    image: node:19-alpine
    working_dir: /usr/src/app
    volumes:
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
      - ./db:/usr/src/app/db/
      - ./src:/usr/src/app/src/
      - /usr/src/app/node_modules/
    restart: unless-stopped
    environment:
      PORT: 3000
    command:
      [
        sh,
        -c,
        "npm i && npm i -g nodemon && npm run dev:server"
      ]

  x-nginx:
    container_name: x-nginx
    image: nginx:1.25.1-alpine-slim
    volumes:
      - ./nginx/dev.nginx.conf:/etc/nginx/nginx.conf
    entrypoint: nginx
    ports:
      - "80:80"
      - "81:81"
    command: [ "-g", "daemon off;" ]

  x-mongo:
    container_name: x-mongo
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - '27017'
    environment:
      PORT: 27017
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: develop

  x-redis:
    container_name: x-redis
    image: redis:7.0.12-alpine
    ports:
      - "6379:6379"
    expose:
      - '6379'
    environment:
      PORT: 6379
      REDIS_ARGS: --requirepass develop
